//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: wallet.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Wallet_AddServiceClient`, then call methods of this protocol to make API calls.
internal protocol Wallet_AddServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Wallet_AddServiceClientInterceptorFactoryProtocol? { get }

  func get(
    _ request: Wallet_Request,
    callOptions: CallOptions?
  ) -> UnaryCall<Wallet_Request, Wallet_Response>

  func update(
    _ request: Wallet_Request,
    callOptions: CallOptions?
  ) -> UnaryCall<Wallet_Request, Wallet_Response>

  func delete(
    _ request: Wallet_Request,
    callOptions: CallOptions?
  ) -> UnaryCall<Wallet_Request, Wallet_Response>
}

extension Wallet_AddServiceClientProtocol {
  internal var serviceName: String {
    return "wallet.AddService"
  }

  /// Unary call to Get
  ///
  /// - Parameters:
  ///   - request: Request to send to Get.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func get(
    _ request: Wallet_Request,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Wallet_Request, Wallet_Response> {
    return self.makeUnaryCall(
      path: Wallet_AddServiceClientMetadata.Methods.get.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInterceptors() ?? []
    )
  }

  /// Unary call to Update
  ///
  /// - Parameters:
  ///   - request: Request to send to Update.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func update(
    _ request: Wallet_Request,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Wallet_Request, Wallet_Response> {
    return self.makeUnaryCall(
      path: Wallet_AddServiceClientMetadata.Methods.update.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateInterceptors() ?? []
    )
  }

  /// Unary call to Delete
  ///
  /// - Parameters:
  ///   - request: Request to send to Delete.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func delete(
    _ request: Wallet_Request,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Wallet_Request, Wallet_Response> {
    return self.makeUnaryCall(
      path: Wallet_AddServiceClientMetadata.Methods.delete.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteInterceptors() ?? []
    )
  }
}

@available(*, deprecated)
extension Wallet_AddServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Wallet_AddServiceNIOClient")
internal final class Wallet_AddServiceClient: Wallet_AddServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Wallet_AddServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Wallet_AddServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the wallet.AddService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Wallet_AddServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Wallet_AddServiceNIOClient: Wallet_AddServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Wallet_AddServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the wallet.AddService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Wallet_AddServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Wallet_AddServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Wallet_AddServiceClientInterceptorFactoryProtocol? { get }

  func makeGetCall(
    _ request: Wallet_Request,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Wallet_Request, Wallet_Response>

  func makeUpdateCall(
    _ request: Wallet_Request,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Wallet_Request, Wallet_Response>

  func makeDeleteCall(
    _ request: Wallet_Request,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Wallet_Request, Wallet_Response>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Wallet_AddServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Wallet_AddServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Wallet_AddServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeGetCall(
    _ request: Wallet_Request,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Wallet_Request, Wallet_Response> {
    return self.makeAsyncUnaryCall(
      path: Wallet_AddServiceClientMetadata.Methods.get.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInterceptors() ?? []
    )
  }

  internal func makeUpdateCall(
    _ request: Wallet_Request,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Wallet_Request, Wallet_Response> {
    return self.makeAsyncUnaryCall(
      path: Wallet_AddServiceClientMetadata.Methods.update.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateInterceptors() ?? []
    )
  }

  internal func makeDeleteCall(
    _ request: Wallet_Request,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Wallet_Request, Wallet_Response> {
    return self.makeAsyncUnaryCall(
      path: Wallet_AddServiceClientMetadata.Methods.delete.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Wallet_AddServiceAsyncClientProtocol {
  internal func get(
    _ request: Wallet_Request,
    callOptions: CallOptions? = nil
  ) async throws -> Wallet_Response {
    return try await self.performAsyncUnaryCall(
      path: Wallet_AddServiceClientMetadata.Methods.get.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInterceptors() ?? []
    )
  }

  internal func update(
    _ request: Wallet_Request,
    callOptions: CallOptions? = nil
  ) async throws -> Wallet_Response {
    return try await self.performAsyncUnaryCall(
      path: Wallet_AddServiceClientMetadata.Methods.update.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateInterceptors() ?? []
    )
  }

  internal func delete(
    _ request: Wallet_Request,
    callOptions: CallOptions? = nil
  ) async throws -> Wallet_Response {
    return try await self.performAsyncUnaryCall(
      path: Wallet_AddServiceClientMetadata.Methods.delete.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Wallet_AddServiceAsyncClient: Wallet_AddServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Wallet_AddServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Wallet_AddServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Wallet_AddServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'get'.
  func makeGetInterceptors() -> [ClientInterceptor<Wallet_Request, Wallet_Response>]

  /// - Returns: Interceptors to use when invoking 'update'.
  func makeUpdateInterceptors() -> [ClientInterceptor<Wallet_Request, Wallet_Response>]

  /// - Returns: Interceptors to use when invoking 'delete'.
  func makeDeleteInterceptors() -> [ClientInterceptor<Wallet_Request, Wallet_Response>]
}

internal enum Wallet_AddServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "AddService",
    fullName: "wallet.AddService",
    methods: [
      Wallet_AddServiceClientMetadata.Methods.get,
      Wallet_AddServiceClientMetadata.Methods.update,
      Wallet_AddServiceClientMetadata.Methods.delete,
    ]
  )

  internal enum Methods {
    internal static let get = GRPCMethodDescriptor(
      name: "Get",
      path: "/wallet.AddService/Get",
      type: GRPCCallType.unary
    )

    internal static let update = GRPCMethodDescriptor(
      name: "Update",
      path: "/wallet.AddService/Update",
      type: GRPCCallType.unary
    )

    internal static let delete = GRPCMethodDescriptor(
      name: "Delete",
      path: "/wallet.AddService/Delete",
      type: GRPCCallType.unary
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Wallet_AddServiceProvider: CallHandlerProvider {
  var interceptors: Wallet_AddServiceServerInterceptorFactoryProtocol? { get }

  func get(request: Wallet_Request, context: StatusOnlyCallContext) -> EventLoopFuture<Wallet_Response>

  func update(request: Wallet_Request, context: StatusOnlyCallContext) -> EventLoopFuture<Wallet_Response>

  func delete(request: Wallet_Request, context: StatusOnlyCallContext) -> EventLoopFuture<Wallet_Response>
}

extension Wallet_AddServiceProvider {
  internal var serviceName: Substring {
    return Wallet_AddServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Get":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Wallet_Request>(),
        responseSerializer: ProtobufSerializer<Wallet_Response>(),
        interceptors: self.interceptors?.makeGetInterceptors() ?? [],
        userFunction: self.get(request:context:)
      )

    case "Update":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Wallet_Request>(),
        responseSerializer: ProtobufSerializer<Wallet_Response>(),
        interceptors: self.interceptors?.makeUpdateInterceptors() ?? [],
        userFunction: self.update(request:context:)
      )

    case "Delete":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Wallet_Request>(),
        responseSerializer: ProtobufSerializer<Wallet_Response>(),
        interceptors: self.interceptors?.makeDeleteInterceptors() ?? [],
        userFunction: self.delete(request:context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Wallet_AddServiceAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Wallet_AddServiceServerInterceptorFactoryProtocol? { get }

  func get(
    request: Wallet_Request,
    context: GRPCAsyncServerCallContext
  ) async throws -> Wallet_Response

  func update(
    request: Wallet_Request,
    context: GRPCAsyncServerCallContext
  ) async throws -> Wallet_Response

  func delete(
    request: Wallet_Request,
    context: GRPCAsyncServerCallContext
  ) async throws -> Wallet_Response
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Wallet_AddServiceAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Wallet_AddServiceServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Wallet_AddServiceServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Wallet_AddServiceServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Get":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Wallet_Request>(),
        responseSerializer: ProtobufSerializer<Wallet_Response>(),
        interceptors: self.interceptors?.makeGetInterceptors() ?? [],
        wrapping: { try await self.get(request: $0, context: $1) }
      )

    case "Update":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Wallet_Request>(),
        responseSerializer: ProtobufSerializer<Wallet_Response>(),
        interceptors: self.interceptors?.makeUpdateInterceptors() ?? [],
        wrapping: { try await self.update(request: $0, context: $1) }
      )

    case "Delete":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Wallet_Request>(),
        responseSerializer: ProtobufSerializer<Wallet_Response>(),
        interceptors: self.interceptors?.makeDeleteInterceptors() ?? [],
        wrapping: { try await self.delete(request: $0, context: $1) }
      )

    default:
      return nil
    }
  }
}

internal protocol Wallet_AddServiceServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'get'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetInterceptors() -> [ServerInterceptor<Wallet_Request, Wallet_Response>]

  /// - Returns: Interceptors to use when handling 'update'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateInterceptors() -> [ServerInterceptor<Wallet_Request, Wallet_Response>]

  /// - Returns: Interceptors to use when handling 'delete'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteInterceptors() -> [ServerInterceptor<Wallet_Request, Wallet_Response>]
}

internal enum Wallet_AddServiceServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "AddService",
    fullName: "wallet.AddService",
    methods: [
      Wallet_AddServiceServerMetadata.Methods.get,
      Wallet_AddServiceServerMetadata.Methods.update,
      Wallet_AddServiceServerMetadata.Methods.delete,
    ]
  )

  internal enum Methods {
    internal static let get = GRPCMethodDescriptor(
      name: "Get",
      path: "/wallet.AddService/Get",
      type: GRPCCallType.unary
    )

    internal static let update = GRPCMethodDescriptor(
      name: "Update",
      path: "/wallet.AddService/Update",
      type: GRPCCallType.unary
    )

    internal static let delete = GRPCMethodDescriptor(
      name: "Delete",
      path: "/wallet.AddService/Delete",
      type: GRPCCallType.unary
    )
  }
}
