// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package inspire_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AddServiceClient is the client API for AddService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddServiceClient interface {
	Inspire(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	SendNotifications(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	GetInspires(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Responses, error)
	UpdateInspire(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	GetLastInspire(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	DeleteInspire(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	GenerateInspireAfterCreatedLastInspire(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type addServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddServiceClient(cc grpc.ClientConnInterface) AddServiceClient {
	return &addServiceClient{cc}
}

func (c *addServiceClient) Inspire(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/inspire.AddService/Inspire", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) SendNotifications(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/inspire.AddService/SendNotifications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) GetInspires(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Responses, error) {
	out := new(Responses)
	err := c.cc.Invoke(ctx, "/inspire.AddService/GetInspires", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) UpdateInspire(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/inspire.AddService/UpdateInspire", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) GetLastInspire(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/inspire.AddService/GetLastInspire", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) DeleteInspire(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/inspire.AddService/DeleteInspire", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) GenerateInspireAfterCreatedLastInspire(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/inspire.AddService/GenerateInspireAfterCreatedLastInspire", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddServiceServer is the server API for AddService service.
// All implementations must embed UnimplementedAddServiceServer
// for forward compatibility
type AddServiceServer interface {
	Inspire(context.Context, *Request) (*Response, error)
	SendNotifications(context.Context, *Request) (*Response, error)
	GetInspires(context.Context, *Request) (*Responses, error)
	UpdateInspire(context.Context, *Request) (*Response, error)
	GetLastInspire(context.Context, *Request) (*Response, error)
	DeleteInspire(context.Context, *Request) (*Response, error)
	GenerateInspireAfterCreatedLastInspire(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAddServiceServer()
}

// UnimplementedAddServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAddServiceServer struct {
}

func (UnimplementedAddServiceServer) Inspire(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inspire not implemented")
}
func (UnimplementedAddServiceServer) SendNotifications(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotifications not implemented")
}
func (UnimplementedAddServiceServer) GetInspires(context.Context, *Request) (*Responses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInspires not implemented")
}
func (UnimplementedAddServiceServer) UpdateInspire(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInspire not implemented")
}
func (UnimplementedAddServiceServer) GetLastInspire(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastInspire not implemented")
}
func (UnimplementedAddServiceServer) DeleteInspire(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInspire not implemented")
}
func (UnimplementedAddServiceServer) GenerateInspireAfterCreatedLastInspire(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateInspireAfterCreatedLastInspire not implemented")
}
func (UnimplementedAddServiceServer) mustEmbedUnimplementedAddServiceServer() {}

// UnsafeAddServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddServiceServer will
// result in compilation errors.
type UnsafeAddServiceServer interface {
	mustEmbedUnimplementedAddServiceServer()
}

func RegisterAddServiceServer(s grpc.ServiceRegistrar, srv AddServiceServer) {
	s.RegisterService(&AddService_ServiceDesc, srv)
}

func _AddService_Inspire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).Inspire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inspire.AddService/Inspire",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).Inspire(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_SendNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).SendNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inspire.AddService/SendNotifications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).SendNotifications(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_GetInspires_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).GetInspires(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inspire.AddService/GetInspires",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).GetInspires(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_UpdateInspire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).UpdateInspire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inspire.AddService/UpdateInspire",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).UpdateInspire(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_GetLastInspire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).GetLastInspire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inspire.AddService/GetLastInspire",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).GetLastInspire(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_DeleteInspire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).DeleteInspire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inspire.AddService/DeleteInspire",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).DeleteInspire(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_GenerateInspireAfterCreatedLastInspire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).GenerateInspireAfterCreatedLastInspire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inspire.AddService/GenerateInspireAfterCreatedLastInspire",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).GenerateInspireAfterCreatedLastInspire(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AddService_ServiceDesc is the grpc.ServiceDesc for AddService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inspire.AddService",
	HandlerType: (*AddServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Inspire",
			Handler:    _AddService_Inspire_Handler,
		},
		{
			MethodName: "SendNotifications",
			Handler:    _AddService_SendNotifications_Handler,
		},
		{
			MethodName: "GetInspires",
			Handler:    _AddService_GetInspires_Handler,
		},
		{
			MethodName: "UpdateInspire",
			Handler:    _AddService_UpdateInspire_Handler,
		},
		{
			MethodName: "GetLastInspire",
			Handler:    _AddService_GetLastInspire_Handler,
		},
		{
			MethodName: "DeleteInspire",
			Handler:    _AddService_DeleteInspire_Handler,
		},
		{
			MethodName: "GenerateInspireAfterCreatedLastInspire",
			Handler:    _AddService_GenerateInspireAfterCreatedLastInspire_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inspire/proto/inspire.proto",
}
