name: Proto Generation Swift

on:
  push:
    paths:
      - '**.proto'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Swift
      run: |
        sudo apt-get update
        sudo apt-get install -y clang libicu-dev
        wget https://download.swift.org/swift-5.9-release/ubuntu2204/swift-5.9-RELEASE/swift-5.9-RELEASE-ubuntu22.04.tar.gz
        tar -xvzf swift-5.9-RELEASE-ubuntu22.04.tar.gz
        sudo mv swift-5.9-RELEASE-ubuntu22.04 /usr/share/swift
        echo "PATH=/usr/share/swift/usr/bin:$PATH" >> $GITHUB_ENV

    - name: Install protoc
      run: |
        sudo apt-get install -y protobuf-compiler

    - name: Install Swift Protobuf Plugin
      run: |
        git clone https://github.com/apple/swift-protobuf.git
        cd swift-protobuf
        swift build -c release
        sudo cp .build/release/protoc-gen-swift /usr/local/bin/
        cd ..

    - name: Download Swift gRPC Plugin
      run: |
        curl -L -o protoc-gen-grpc-swift https://github.com/grpc/grpc-swift/releases/latest/download/protoc-gen-grpc-swift-ubuntu22.04
        file protoc-gen-grpc-swift
        chmod +x protoc-gen-grpc-swift
        sudo mv protoc-gen-grpc-swift /usr/local/bin/

    - name: Generate Swift code from proto files
      run: |
        mkdir -p Generated
        protoc \
          --proto_path=. \
          --swift_out=Generated \
          --grpc-swift_out=Generated \
          $(find . -name '*.proto' \
            ! -path "./swift-protobuf/Protos/upstream/*" \
            ! -path "./swift-protobuf/PluginExamples/*")


    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add Generated
        git commit -m "Auto-generate Swift code from proto files" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
